Desktop version of Portfolio project
jonas-45/JonasPotfolio pull request #4
Opened 2022-12-14 17:38 UTC by jonas-45

This project is the desktop version of the mobile portfolio project and a number of changes have been added.

1. The whole site is fully responsive adapting to both desktop and mobile screens
2. The navigation menu has menu items displayed as text when in desktop mode but displayed as an overflow icon when in mobile view mode
3. Grid and Flexbox are used throughout in designing the page

2022-12-14 22:05 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @jonas-45 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️
* Great looking website 💯 

## Required Changes:
_Kindly check the comments below_


------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 22:05 UTC, ha-manel commented on index.html
> +                    <li>Contact</li>
- [ ] kindly make these nav-items `a` tags where the `href` attribute is the id of the section that you want the link to take to, e.g: `<a href="#contact">Contact</a>` clicking on this link will take you to the section that has `id="contact"` which should be the contact section (this is an example but it applies to the other links too) 👍

2022-12-14 22:05 UTC, ha-manel commented on index.html
> +              <!-- <img alt="works1-image" src="images/card1.png" id="card1"> -->
- [ ] Kindly remove commented unused pieces of code to improve readability and to have a clean codebase and not a messy one 💯

2022-12-14 22:05 UTC, ha-manel commented on index.html
> +                <h1 class="desktop-title">Tonic</h1>
- [ ] Kindly replace these `h1` tags (and all the following ones) with another `hx` tag (like `h2`...) because in a webpage there should be only one `h1` tag which is the main heading of the page 👍

2022-12-14 22:05 UTC, ha-manel commented on index.html
> -            <p class="social-title">LET'S CONNECT</p>
- [ ] Kindly remove the border from this paragraph to match the design in Figma 💯 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/207723104-b054e42d-db58-48ee-823f-a012d7f3cc72.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/207723147-43f49987-63e5-441a-a91b-d0cec1cdda20.png)

2022-12-14 22:05 UTC, ha-manel commented on index.html
> +              <button class="resume-btn">Get my resume</button>
- [ ] Kindly add button interaction styles to this button (hover, active...) as shown in Figma 👍 

![image](https://user-images.githubusercontent.com/50721479/207724313-de0905fd-4cd5-468e-bdce-76c593b5f2a9.png)

![image](https://user-images.githubusercontent.com/50721479/207724359-176eee0d-f0cb-4655-8e15-4dee21545b56.png)

2022-12-15 00:06 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @jonas-45, 

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://i.pinimg.com/originals/f8/3d/cf/f83dcf0c379de146ef962251952577ab.gif">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 00:06 UTC, brainconnect93 commented on style.css
> +@media screen and (min-width: 768px) {
- [x] [OPTIONAL] I noticed multiple usage of the @media screen and (min-width: 768px) in your styling. I would strongly suggest you use only one `@media screen and (min-width: 768px)` and have all your styling properties nested inside, with this, you will follow the `DRY` method of the best HTML and CSS coding practices

2022-12-15 00:09 UTC, merged